name: chat_flutter.
version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  web_socket_channel: ^2.4.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true

assets:
  - .env